imports:
  features: features.yml
types:
  SeedWorkspaceConfiguration:
    properties:
      irVersion: string
      language: optional<Language>
      defaultCustomConfig: optional<map<string, unknown>>
      defaultOutputMode: OutputMode
      generatorType: GeneratorType
      docker: string
      dockerCommand: optional<DockerCommand>
      local: optional<LocalBuildInfo>
      customFixtureConfig: 
        type: optional<FixtureConfigurations>
        docs: |
          Configuration that will be used for any custom fixture specified by --custom-fixture
      fixtures:
        type: optional<map<string, list<FixtureConfigurations>>>
      scripts: optional<list<ScriptConfig>>
      allowedFailures: 
        type: optional<list<string>>
        docs: | 
          List any fixtures that are okay to fail. For normal fixtures 
          just list the fixture name. For configured fixture list {fixture}:{outputFolder}.
      features: optional<features.GeneratorFeatures>
  
  LocalBuildInfo: 
    properties: 
      workingDirectory: 
        type: string
        docs: | 
          The working directory for the generator. 
      buildCommand: 
        type: list<string>
        docs: | 
          The command to build the generator locally. 
          `yarn workspace @fern-api/openapi-generator build` for example. 
      runCommand:
        type: string
        docs: | 
          The command to run the generator locally. 
          `node generators/openapi/dist/cli.cjs` for example.
      env: 
        type: optional<map<string, string>>
        docs: | 
          Environment variables to set when running the generator locally.

  DockerCommand: 
    discriminated: false
    union: 
      - string
      - list<string>

  ScriptConfig:
    properties:
      docker: string
      commands: list<string>

  Language:
    enum:
      - python
      - java
      - typescript
      - go
      - ruby
      - csharp
      - swift

  GeneratorType:
    enum:
      - SDK
      - Model
      - Server
      - Documentation

  FixtureConfigurations:
    properties:
      publishConfig: unknown
      publishMetadata: unknown
      customConfig: unknown
      readmeConfig: optional<ReadmeConfig>
      audiences: optional<list<string>>
      outputFolder: string
      outputVersion: optional<string>
      outputMode: 
        type: optional<OutputMode>
        docs: Overrides the default output mode

  ReadmeConfig:
    properties:
      defaultEndpoint: optional<ReadmeEndpoint>
      bannerLink: optional<string>
      apiReferenceLink: optional<string>
      features: optional<map<string, list<ReadmeEndpoint>>>

  ReadmeEndpoint:
    discriminated: false
    union: 
      - string
      - ReadmeEndpointObject

  ReadmeEndpointObject:
    properties:
      method: string
      path: string
      stream: optional<boolean>
  
  OutputMode: 
    enum: 
      - github
      - local_files
      - publish

