# yaml-language-server: $schema=https://raw.githubusercontent.com/fern-api/fern/main/fern.schema.json

types:
  MyResponse:
    properties:
      id: string
      name: optional<string>

service:
  auth: false
  base-path: ""
  endpoints:
    hello:
      path: /hello
      method: POST
      request:
        name: MyRequest
        body:
          properties:
            num_events: integer
      response:
        type: MyResponse
      examples:
        - request:
            num_events: 5
          response:
            body:
              id: "123"
              name: "hello"
          code-samples:
          - name: curl
            sdk: curl
            code: |
              curl -X POST "http://localhost:8080/hello"
              -H "Content-Type: application/json"
              -d '{"num_events": 5}'
          - name: python
            sdk: python
            code: |
              import requests
              response = requests.post("http://localhost:8080/hello", json={"num_events": 5})
              print(response.json())

