openapi: 3.0.1
info:
  title: server-sent-events
  version: ''
paths:
  /stream:
    post:
      operationId: completions_stream
      tags:
        - Completions
      parameters: []
      responses:
        '204':
          description: ''
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
              required:
                - query
components:
  schemas:
    StreamedCompletion:
      title: StreamedCompletion
      type: object
      properties:
        delta:
          type: string
        tokens:
          type: integer
          nullable: true
      required:
        - delta
  securitySchemes: {}
