openapi: 3.0.1
info:
  title: code-samples
  version: ''
paths:
  /hello:
    post:
      operationId: service_hello
      tags:
        - Service
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MyResponse'
              examples:
                Example1:
                  value:
                    id: '123'
                    name: hello
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                num_events:
                  type: integer
                  example: 5
              required:
                - num_events
            examples:
              Example1:
                value:
                  num_events: 5
components:
  schemas:
    MyResponse:
      title: MyResponse
      type: object
      properties:
        id:
          type: string
          example: '123'
        name:
          type: string
          nullable: true
      required:
        - id
  securitySchemes: {}
